import type { DocsContentText } from "@/content/docs/types";
import type { PartialText } from "@/i18n/create-text-query";

const it: PartialText<DocsContentText> = {
  quickstart: {
    "toc.1-install": "Installa", "toc.2-wrap": "Avvolgi l’app", "toc.3-links": "Usa IntentLink", intro: "Aggiungi azioni basate sull’intento alla tua app Next.js in tre passaggi.", installHeading: "1 · Installa", wrapHeading: "2 · Avvolgi l’app una volta", wrapBody: "Aggiungi `IntentProvider` una sola volta nel layout radice. Eseguirà un unico motore di intento condiviso per tutto ciò che contiene.", linksHeading: "3 · Usa IntentLink", linksBody: "Usa `IntentLink` come un normale link Next.js e inserisci in `onIntent` il lavoro che vuoi iniziare in anticipo.", closing: "Per la maggior parte delle app non serve altro. La libreria non esegue il prefetch da sola: sei tu a decidere cosa fa `onIntent`.",
  },
  "how-it-works": {
    "toc.observe": "Osserva", "toc.decide": "Decidi", "toc.fire": "Avvia il lavoro", "toc.devices": "Desktop e dispositivi mobili", "toc.physics": "L’idea della fisica", intro: "intent-link osserva come l’utente si muove nella pagina e stima a quale obiettivo visibile si sta avvicinando. Quando il segnale è abbastanza forte, chiama la funzione `onIntent` di quell’obiettivo.", observeHeading: "1 · Osserva il movimento", observeBody: "Sul desktop legge il movimento del puntatore. Sui dispositivi touch legge lo scorrimento. Si attiva solo quando l’utente interagisce e torna inattivo quando il movimento si ferma.", decideHeading: "2 · Decidi l’obiettivo", decideBody: "Il motore confronta il movimento dell’utente con gli obiettivi visibili. Gli obiettivi fuori dalla viewport non partecipano ai calcoli.", fireHeading: "3 · Avvia il lavoro", fireBody: "Quando un obiettivo diventa abbastanza probabile, il suo callback `onIntent` viene eseguito una volta. Può essere eseguito di nuovo se l’utente si allontana e poi ritorna.", devicesHeading: "Desktop e dispositivi mobili", "devices.desktop": "Sul desktop il motore segue il movimento bidimensionale del puntatore.", "devices.mobile": "Sui dispositivi mobili segue lo scorrimento verticale e si attiva al primo scorrimento.", "devices.visible": "Gli obiettivi nascosti o fuori dallo schermo vengono ignorati, compresi quelli nascosti dal CSS responsivo.", physicsHeading: "L’idea della fisica", physicsEnergy: "Immagina ogni obiettivo come un piccolo pozzo gravitazionale. Il movimento crea **energia cinetica**, mentre la distanza dall’obiettivo crea **energia potenziale**. Un puntatore o uno scorrimento veloce ha ancora slancio; un movimento lento vicino a un obiettivo sembra invece stabilizzarsi lì. Il motore usa una regola simile alla termodinamica per considerare più probabili queste destinazioni a bassa energia.", physicsKalman: "I dati di movimento del browser contengono piccoli salti ed errori. Un **filtro di Kalman** attenua questo rumore prima del calcolo fisico. In parole semplici, aiuta a distinguere un movimento intenzionale da misurazioni instabili. Tutto avviene dentro la libreria; la tua app riceve soltanto `onIntent`.", paperNote: "[Leggi l’articolo di ricerca](https://intentlink.dev/paper). Questo collegamento è provvisorio fino alla pubblicazione su ACM.",
  },
  "intent-provider": {
    "toc.usage": "Utilizzo", "toc.notes": "Note", intro: "Aggiungi `IntentProvider` una volta vicino alla radice dell’app. Esegue il motore di intento condiviso per `IntentLink` e `useIntentTarget`.", usageHeading: "Utilizzo", notesHeading: "Note", "notes.once": "Usa un solo provider per app e non annidare più provider.", "notes.props": "Richiede soltanto `children`; non ci sono altre impostazioni.", "notes.client": "Include il proprio confine client, quindi puoi importarlo direttamente da un layout server di Next.js.",
  },
  "intent-link": {
    "toc.props": "Props", "toc.onintent": "onIntent", "toc.tuning": "importance e cost", "toc.example": "Esempio", intro: "Usa `IntentLink` dove useresti normalmente il `Link` di Next.js. Aggiungi a `onIntent` il lavoro che vuoi iniziare prima del clic.", propsHeading: "Props", "col.prop": "Prop", "col.type": "Tipo", "col.default": "Predefinito", "col.description": "Descrizione", "prop.href": "Obbligatorio. Uguale al Link di Next.js.", "prop.importance": "Quanto facilmente deve iniziare il lavoro.", "prop.cost": "Quanto prudente deve essere la previsione.", "prop.onIntent": "Chiamato una volta quando è probabile che l’utente scelga questo link.", "prop.rest": "Qualsiasi prop di Link di Next.js o di un’ancora, inclusi className, style e ref.", prefetchNote: "`IntentLink` disattiva il prefetch automatico di Next.js. Per il prefetch predittivo, chiama `router.prefetch()` dentro `onIntent`.", onIntentHeading: "onIntent", onIntentBody: "Il callback non riceve argomenti e non restituisce alcun valore. Viene eseguito una volta per ogni avvicinamento e si riattiva quando l’utente si allontana.", tuningHeading: "importance e cost", tuningBody: "Queste impostazioni sono facoltative. La maggior parte delle app dovrebbe mantenere i valori predefiniti.", "tuning.importance": "`importance` controlla quanto facilmente inizia il lavoro. Valore predefinito: `medium`.", "tuning.cost": "`cost` controlla la prudenza della previsione. Valore predefinito: `low`.", "tuning.defaults": "Modifica questi valori solo dopo aver provato il lavoro reale sia sul desktop sia sui dispositivi mobili.", exampleHeading: "Esempio",
  },
  "use-intent-target": {
    "toc.button": "Utilizzo di base", "toc.options": "Opzioni", "toc.third-party": "Componenti di terze parti", intro: "`useIntentTarget` aggiunge il rilevamento dell’intento a un pulsante, una scheda o qualsiasi altro elemento HTML. Collega il ref restituito all’elemento che vuoi osservare.", buttonHeading: "Utilizzo di base", buttonBody: "Chiama l’hook in un componente client e collega il ref restituito a un elemento HTML.", optionsHeading: "Opzioni", "options.onIntent": "`onIntent`: il lavoro da eseguire quando l’elemento diventa un obiettivo probabile.", "options.importance": "`importance`: valore facoltativo `high`, `medium` o `low`. Predefinito: `medium`.", "options.cost": "`cost`: valore facoltativo `high`, `medium` o `low`. Predefinito: `low`.", thirdPartyHeading: "Componenti di terze parti", thirdPartyBody: "Se il componente inoltra il ref a un vero elemento HTML, collegalo direttamente.", wrapperBody: "Se non inoltra i ref, avvolgilo in un elemento nativo e collega il ref all’elemento contenitore.",
  },
  "custom-intent-components": {
    "toc.intent-button": "IntentButton", "toc.intent-button-usage": "Utilizzo", "toc.intent-article": "IntentArticle", "toc.intent-article-usage": "Utilizzo", intro: "Se hai molti obiettivi dello stesso tipo, avvolgi `useIntentTarget` una volta e riutilizza il componente ottenuto.", buttonHeading: "Un IntentButton riutilizzabile", buttonBody: "Accetta le normali props di un pulsante insieme a `onIntent`, `importance` e `cost`.", articleHeading: "Un IntentArticle riutilizzabile", articleBody: "Lo stesso modello funziona per schede di prodotti e altri contenitori semantici.", usageHeading: "Utilizzo",
  },
  examples: {
    "toc.route": "Prefetch di una rotta", "toc.data": "Prepara i dati", "toc.asset": "Precarica un’immagine", "toc.action": "Prepara un componente", intro: "Usa `onIntent` per iniziare un lavoro di preparazione sicuro e ripetibile. Le azioni irreversibili, come acquistare, inviare un messaggio o inviare un modulo, devono attendere il clic effettivo.", routeHeading: "Prefetch di una rotta", routeBody: "Il caso d’uso più comune con Next.js.", dataHeading: "Prepara i dati", dataBody: "Inserisci nella cache della libreria dati le informazioni necessarie alla schermata successiva.", assetHeading: "Precarica un’immagine", assetBody: "Inizia a caricare una risorsa pesante prima della navigazione.", actionHeading: "Prepara un componente", actionBody: "Usa `useIntentTarget` quando l’obiettivo non è un link.",
  },
  troubleshooting: {
    "toc.nothing": "Non succede nulla", "toc.prefetch": "Prefetch imprevisto", "toc.custom": "Ref di un componente personalizzato", "toc.mobile": "Test sui dispositivi mobili", "toc.development": "Modalità di sviluppo", nothingHeading: "onIntent non viene eseguito", "nothing.provider": "C’è un `IntentProvider` sopra questi link?", "nothing.callback": "L’obiettivo ha un callback `onIntent`? Gli obiettivi senza callback non vengono registrati.", "nothing.input": "Muovi il puntatore sul desktop o scorri su un dispositivo mobile. Il motore resta inattivo fino alla prima interazione.", "nothing.size": "Verifica che l’obiettivo sia visibile e abbia larghezza e altezza reali.", "nothing.wiring": "Prova temporaneamente `importance=\"high\"` e `cost=\"low\"` per verificare il collegamento, poi ripristina i valori predefiniti.", prefetchHeading: "Una rotta viene caricata senza onIntent", prefetchBody: "Cerca un altro `Link` di Next.js che punti alla stessa rotta, compresi i link nascosti nei layout responsivi. Cerca anche chiamate dirette a `router.prefetch()`.", customHeading: "Un componente personalizzato non funziona", customBody: "Il componente deve inoltrare il ref a un vero elemento HTML. Altrimenti collega il ref di intento a un contenitore nativo, come un `div`.", mobileHeading: "Test sui dispositivi mobili", mobileBody: "Usa un vero dispositivo touch oppure attiva l’emulazione del tocco negli strumenti del browser e poi scorri. Restringere soltanto una finestra desktop potrebbe non attivare il comportamento mobile.", developmentHeading: "Sviluppo e produzione", developmentBody: "Verifica il comportamento importante anche in una build di produzione. I controlli di sviluppo di React e gli strumenti del framework possono far apparire callback o richieste di rete diversi dalla produzione.",
  },
  changelog: {
    "toc.v1013": "1.0.13", v1013Heading: "1.0.13 (attuale)", "v1013.api": "Aggiunge `useIntentTarget` per pulsanti, schede e componenti di terze parti.", "v1013.visibility": "Solo gli obiettivi visibili partecipano alla previsione.", "v1013.behavior": "`onIntent` è ora un semplice callback void e lo stato interno della previsione non fa più parte dell’API pubblica.", "v1013.performance": "Migliora la registrazione, il rendering e le prestazioni nelle pagine con molti obiettivi.", history: "Consulta la [cronologia completa delle versioni](https://www.npmjs.com/package/intent-link?activeTab=versions) su npm.",
  },
};

export { it };
