import type { DocsContentText } from "@/content/docs/types";
import type { PartialText } from "@/i18n/create-text-query";

const tr: PartialText<DocsContentText> = {
  quickstart: {
    "toc.1-install": "Kurulum", "toc.2-wrap": "Uygulamayı sarın", "toc.3-links": "IntentLink kullanın", intro: "Next.js uygulamanıza üç adımda niyet duyarlı davranış ekleyin.", installHeading: "1 · Kurulum", wrapHeading: "2 · Uygulamayı bir kez sarın", wrapBody: "Kök yerleşime bir kez `IntentProvider` ekleyin. İçindeki her şey için tek bir paylaşılan niyet motoru çalıştırır.", linksHeading: "3 · IntentLink kullanın", linksBody: "`IntentLink` bileşenini normal bir Next.js bağlantısı gibi kullanın ve erken başlatmak istediğiniz işi `onIntent` içine koyun.", closing: "Çoğu uygulama için gerekenlerin tamamı budur. Kitaplık kendiliğinden ön yükleme yapmaz; `onIntent` işlevinin ne yapacağına siz karar verirsiniz.",
  },
  "how-it-works": {
    "toc.observe": "Gözlemle", "toc.decide": "Karar ver", "toc.fire": "İşi başlat", "toc.devices": "Masaüstü ve mobil", "toc.physics": "Fizik fikri", intro: "intent-link, kullanıcının sayfadaki hareketini izler ve hangi görünür hedefe yaklaştığını tahmin eder. Sinyal yeterince güçlü olduğunda o hedefin `onIntent` işlevini çağırır.", observeHeading: "1 · Hareketi gözlemle", observeBody: "Masaüstünde işaretçi hareketini, dokunmatik cihazlarda kaydırmayı okur. Yalnızca kullanıcı etkileşim kurduğunda uyanır ve hareket durduğunda yeniden dinlenir.", decideHeading: "2 · Hedefe karar ver", decideBody: "Motor, kullanıcının hareketini görünür niyet hedefleriyle karşılaştırır. Görüntü alanının dışındaki hedefler hesaplamalara katılmaz.", fireHeading: "3 · İşi başlat", fireBody: "Bir hedef yeterince olası hâle geldiğinde `onIntent` callback’i bir kez çalışır. Kullanıcı uzaklaşıp daha sonra yeniden yaklaşırsa tekrar çalışabilir.", devicesHeading: "Masaüstü ve mobil", "devices.desktop": "Masaüstünde motor, işaretçinin iki boyutlu hareketini izler.", "devices.mobile": "Mobilde dikey kaydırmayı izler ve ilk kaydırmada etkinleşir.", "devices.visible": "Duyarlı CSS ile gizlenen öğeler dâhil, gizli veya ekran dışındaki hedefler yok sayılır.", physicsHeading: "Fizik fikri", physicsEnergy: "Her hedefi küçük bir yerçekimi kuyusu gibi düşünün. Hareket **kinetik enerji**, hedefe olan uzaklık ise **potansiyel enerji** oluşturur. Hızlı bir işaretçi veya kaydırma hâlâ ivmeye sahiptir; hedefin yakınındaki yavaş hareket ise oraya yerleşiyor gibi görünür. Motor, termodinamiğe benzeyen bir kuralla bu düşük enerjili varış noktalarını daha olası seçimler olarak değerlendirir.", physicsKalman: "Tarayıcı hareket verilerinde küçük sıçramalar ve hatalar bulunur. Bir **Kalman filtresi**, fizik hesabından önce bu gürültüyü yumuşatır. Basitçe, kasıtlı hareket ile kararsız ölçümleri ayırmaya yardımcı olur. Bunların tamamı kitaplığın içinde kalır; uygulamanız yalnızca `onIntent` alır.", paperNote: "[Araştırma makalesini okuyun](https://intentlink.dev/paper). ACM’de yayımlanana kadar bu bağlantı geçicidir.",
  },
  "intent-provider": {
    "toc.usage": "Kullanım", "toc.notes": "Notlar", intro: "Uygulamanın köküne yakın bir yere bir kez `IntentProvider` ekleyin. `IntentLink` ve `useIntentTarget` için paylaşılan niyet motorunu çalıştırır.", usageHeading: "Kullanım", notesHeading: "Notlar", "notes.once": "Uygulama başına yalnızca bir provider kullanın; provider’ları iç içe yerleştirmeyin.", "notes.props": "Yalnızca `children` gerekir; başka ayarı yoktur.", "notes.client": "Kendi istemci sınırını içerdiği için doğrudan bir Next.js sunucu yerleşiminden içe aktarılabilir.",
  },
  "intent-link": {
    "toc.props": "Props", "toc.onintent": "onIntent", "toc.tuning": "importance ve cost", "toc.example": "Örnek", intro: "Normalde Next.js `Link` kullanacağınız yerde `IntentLink` kullanın. Tıklamadan önce başlatmak istediğiniz işi `onIntent` içine ekleyin.", propsHeading: "Props", "col.prop": "Prop", "col.type": "Tür", "col.default": "Varsayılan", "col.description": "Açıklama", "prop.href": "Zorunlu. Next.js Link ile aynıdır.", "prop.importance": "İşin ne kadar kolay başlatılacağını belirler.", "prop.cost": "Tahminin ne kadar temkinli olacağını belirler.", "prop.onIntent": "Kullanıcının bu bağlantıyı seçmesi olası olduğunda bir kez çağrılır.", "prop.rest": "className, style ve ref dâhil tüm Next.js Link veya bağlantı öğesi prop’ları.", prefetchNote: "`IntentLink`, Next.js’in otomatik ön yüklemesini kapatır. Tahmine dayalı ön yükleme için `onIntent` içinde `router.prefetch()` çağırın.", onIntentHeading: "onIntent", onIntentBody: "Bu callback argüman almaz ve değer döndürmez. Her yaklaşmada bir kez çalışır; kullanıcı uzaklaştığında yeniden hazır hâle gelir.", tuningHeading: "importance ve cost", tuningBody: "Bu ayarlar isteğe bağlıdır. Çoğu uygulama varsayılan değerleri korumalıdır.", "tuning.importance": "`importance`, işin ne kadar kolay başlayacağını kontrol eder. Varsayılan: `medium`.", "tuning.cost": "`cost`, tahminin ne kadar temkinli olacağını kontrol eder. Varsayılan: `low`.", "tuning.defaults": "Bu değerleri yalnızca gerçek işi hem masaüstünde hem mobilde test ettikten sonra değiştirin.", exampleHeading: "Örnek",
  },
  "use-intent-target": {
    "toc.button": "Temel kullanım", "toc.options": "Seçenekler", "toc.third-party": "Üçüncü taraf bileşenler", intro: "`useIntentTarget`, bir düğmeye, karta veya başka bir HTML öğesine niyet algılama ekler. Döndürülen ref’i izlemek istediğiniz öğeye bağlayın.", buttonHeading: "Temel kullanım", buttonBody: "Hook’u bir istemci bileşeninde çağırın ve döndürülen ref’i tek bir HTML öğesine bağlayın.", optionsHeading: "Seçenekler", "options.onIntent": "`onIntent`: öğe olası bir hedef olduğunda çalıştırılacak iş.", "options.importance": "`importance`: isteğe bağlı `high`, `medium` veya `low`. Varsayılan: `medium`.", "options.cost": "`cost`: isteğe bağlı `high`, `medium` veya `low`. Varsayılan: `low`.", thirdPartyHeading: "Üçüncü taraf bileşenler", thirdPartyBody: "Bileşen ref’i gerçek bir HTML öğesine iletiyorsa doğrudan bağlayın.", wrapperBody: "Ref iletmiyorsa bileşeni yerel bir öğeyle sarın ve ref’i bu sarmalayıcıya bağlayın.",
  },
  "custom-intent-components": {
    "toc.intent-button": "IntentButton", "toc.intent-button-usage": "Kullanım", "toc.intent-article": "IntentArticle", "toc.intent-article-usage": "Kullanım", intro: "Aynı türden çok sayıda hedefiniz varsa `useIntentTarget` işlevini bir kez sarın ve oluşan bileşeni yeniden kullanın.", buttonHeading: "Yeniden kullanılabilir IntentButton", buttonBody: "Normal düğme prop’larının yanı sıra `onIntent`, `importance` ve `cost` kabul eder.", articleHeading: "Yeniden kullanılabilir IntentArticle", articleBody: "Aynı yaklaşım ürün kartları ve diğer anlamsal kapsayıcılar için de çalışır.", usageHeading: "Kullanım",
  },
  examples: {
    "toc.route": "Rotayı önceden yükle", "toc.data": "Verileri hazırla", "toc.asset": "Görseli önceden yükle", "toc.action": "Bileşeni hazırla", intro: "Güvenli ve tekrarlanabilir hazırlık işlerini başlatmak için `onIntent` kullanın. Satın alma, mesaj gönderme veya form gönderme gibi geri alınamaz işlemler gerçek tıklamayı beklemelidir.", routeHeading: "Rotayı önceden yükle", routeBody: "En yaygın Next.js kullanım şekli.", dataHeading: "Verileri hazırla", dataBody: "Sonraki ekranın ihtiyaç duyduğu bilgileri veri kitaplığınızın önbelleğine yerleştirin.", assetHeading: "Görseli önceden yükle", assetBody: "Gezinmeden önce büyük bir kaynağı yüklemeye başlayın.", actionHeading: "Bileşeni hazırla", actionBody: "Hedef bir bağlantı değilse `useIntentTarget` kullanın.",
  },
  troubleshooting: {
    "toc.nothing": "Hiçbir şey olmuyor", "toc.prefetch": "Beklenmeyen ön yükleme", "toc.custom": "Özel bileşen ref’i", "toc.mobile": "Mobil test", "toc.development": "Geliştirme modu", nothingHeading: "onIntent çalışmıyor", "nothing.provider": "Bu bağlantıların üzerinde bir `IntentProvider` var mı?", "nothing.callback": "Hedefte bir `onIntent` callback’i var mı? Callback’i olmayan hedefler kaydedilmez.", "nothing.input": "Masaüstünde işaretçiyi hareket ettirin veya mobilde kaydırın. Motor ilk etkileşime kadar dinlenir.", "nothing.size": "Hedefin görünür olduğunu ve gerçek genişlik ile yüksekliğe sahip olduğunu doğrulayın.", "nothing.wiring": "Bağlantıyı kontrol etmek için geçici olarak `importance=\"high\"` ve `cost=\"low\"` deneyin, ardından varsayılanlara dönün.", prefetchHeading: "Bir rota onIntent olmadan önceden yükleniyor", prefetchBody: "Duyarlı yerleşimlerde gizli bağlantılar dâhil, aynı rotayı gösteren başka bir Next.js `Link` olup olmadığını kontrol edin. Doğrudan `router.prefetch()` çağrılarını da arayın.", customHeading: "Özel bir bileşen çalışmıyor", customBody: "Bileşen ref’ini gerçek bir HTML öğesine iletmelidir. İletmiyorsa niyet ref’ini `div` gibi yerel bir sarmalayıcıya bağlayın.", mobileHeading: "Mobilde test", mobileBody: "Gerçek bir dokunmatik cihaz kullanın veya tarayıcı geliştirici araçlarında dokunma emülasyonunu etkinleştirip kaydırın. Yalnızca masaüstü penceresini daraltmak mobil davranışı etkinleştirmeyebilir.", developmentHeading: "Geliştirme ve üretim", developmentBody: "Önemli davranışı üretim derlemesinde de doğrulayın. React geliştirme kontrolleri ve çatı araçları, callback’lerin veya ağ isteklerinin üretimden farklı görünmesine yol açabilir.",
  },
  changelog: {
    "toc.v1013": "1.0.13", v1013Heading: "1.0.13 (güncel)", "v1013.api": "Düğmeler, kartlar ve üçüncü taraf bileşenler için `useIntentTarget` eklendi.", "v1013.visibility": "Yalnızca görünür hedefler tahmin çalışmasına katılır.", "v1013.behavior": "`onIntent` artık basit bir void callback’tir; iç tahmin durumu genel API’nin parçası değildir.", "v1013.performance": "Kayıt, render ve çok hedefli sayfalardaki performans iyileştirildi.", history: "[Tüm sürüm geçmişini](https://www.npmjs.com/package/intent-link?activeTab=versions) npm’de görüntüleyin.",
  },
};

export { tr };
